In [ ]:
from numpy.random import rand
from numpy.linalg import solve, inv
import numpy as np

In [ ]:
a = np.array([[1, 2, 3], [3, 4, 6.7], [5, 9.0, 5]])
# a.transpose()
a

array([[1. , 2. , 3. ],
       [3. , 4. , 6.7],
       [5. , 9. , 5. ]])

In [ ]:
a.transpose()

array([[1. , 3. , 5. ],
       [2. , 4. , 9. ],
       [3. , 6.7, 5. ]])

In [ ]:
inv(a)

array([[-2.27683616,  0.96045198,  0.07909605],
       [ 1.04519774, -0.56497175,  0.1299435 ],
       [ 0.39548023,  0.05649718, -0.11299435]])

In [ ]:
a.shape

(3, 3)

In [ ]:
b =  np.array([3, 2, 1])
b.shape

(3,)

In [ ]:
solve(a, b)  # solve the equation ax = b

array([-4.83050847,  2.13559322,  1.18644068])

In [ ]:
c = rand(3, 3)
c

array([[0.31621144, 0.34568338, 0.47130902],
       [0.31120923, 0.46884536, 0.44715498],
       [0.93254503, 0.84579976, 0.22794675]])

In [ ]:
c = rand(3, 3) * 20  # create a 3x3 random matrix of values within [0,1] scaled by 20

In [ ]:
c

array([[18.87959175, 12.67980686,  3.01569117],
       [14.09494794,  4.36485629, 10.16933953],
       [ 9.43746541,  9.00887372,  8.56417714]])

In [ ]:
np.dot(a, c)  # matrix multiplication

array([[ 64.22713407,  37.73259472,  43.92396322],
       [147.63359234,  92.81166944, 110.34170523],
       [178.17363378, 165.58058555, 144.05199694]])

In [ ]:
a @ c  # new way of Mat mul

array([[ 64.22713407,  37.73259472,  43.92396322],
       [147.63359234,  92.81166944, 110.34170523],
       [178.17363378, 165.58058555, 144.05199694]])

In [2]:
w=[1,2,3]
x=[5,6,7]

sum=0
for i in range(len(w)):
  sum = sum + w[i]*x[i]
print (sum)


38


In [7]:
wa.shape

(3,)

In [8]:
wa * xa

array([ 5, 12, 21])

In [11]:
w=[ [1,2,3],
    [9,10,11]
  ]
x=[5,6,7]
import numpy as np
wa = np.array(w)
xa = np.array(x)
print (np.dot(wa,xa))

[ 38 182]


In [12]:
def sigmoid(x):
  return 1/(1+np.exp(-x))

In [19]:
sigmoid(1)

0.7310585786300049